name: Build Docs and Commit PDFs

on:
  workflow_dispatch:  # Allow manual trigger

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
    # 1. Check out the control repository (docs-builder)
    - name: Checkout Control Repo
      uses: actions/checkout@v3

    # 2. Clone Required Repositories
    - name: Clone Repositories
      run: |
        mkdir -p $GITHUB_WORKSPACE/localrender
        cd $GITHUB_WORKSPACE

        # Clone repositories dynamically
        REPOS=("mkdocs" "theme" "secops" "cloud" "ot" "sase" "landing-page")
        for REPO in "${REPOS[@]}"; do
          git clone https://${{ secrets.PAT }}@github.com/${{ github.repository_owner }}/$REPO.git $REPO
        done

    # 3. Install MkDocs and Dependencies
    - name: Install MkDocs and Plugins
      run: |
        pip install \
        mkdocs \
        mkdocs-material \
        mkdocs-exclude \
        mkdocs-awesome-pages-plugin \
        mkdocs-glightbox \
        mkdocs-gh-admonitions \
        mkdocs-literate-nav


    - name: Install wkhtmltopdf
      run: sudo apt-get update && sudo apt-get install -y wkhtmltopdf
      
    # 4. Build and Generate PDFs for Each Repository
    - name: Build and Generate PDFs
      run: |
        # Define repositories to process
        REPOS=("secops" "cloud" "ot" "sase")
        OUTPUT_DIR=$GITHUB_WORKSPACE/outputs
        mkdir -p $OUTPUT_DIR

        for REPO in "${REPOS[@]}"; do
          # Prepare the build environment
          mkdir -p $GITHUB_WORKSPACE/localrender/$REPO
          cp -R $GITHUB_WORKSPACE/landing-page/* $GITHUB_WORKSPACE/localrender/$REPO
          cp -R $GITHUB_WORKSPACE/$REPO $GITHUB_WORKSPACE/localrender/$REPO/docs
          cp -R $GITHUB_WORKSPACE/theme $GITHUB_WORKSPACE/localrender/$REPO/docs
          cp -R $GITHUB_WORKSPACE/theme/* $GITHUB_WORKSPACE/localrender/$REPO

          # Generate the mkdocs.yml for this repository
          echo "site_name: '${REPO^} Hands-on Labs'" > $GITHUB_WORKSPACE/localrender/$REPO/mkdocs.yml
          echo "INHERIT: docs/theme/mkdocs.yml" >> $GITHUB_WORKSPACE/localrender/$REPO/mkdocs.yml

          # Build the MkDocs site
          cd $GITHUB_WORKSPACE/localrender/$REPO
          mkdocs build -d site

          # Generate the PDF for this repository
          cd $GITHUB_WORKSPACE/localrender/$REPO/site
          wkhtmltopdf \
            --enable-local-file-access \
            --footer-center '[page]' \
            --margin-top 15mm \
            --margin-bottom 15mm \
            $(find . -name "*.html" | sort) $OUTPUT_DIR/hands-on-lab_${REPO}.pdf
        done

    # 5. Commit the PDFs to the Control Repo
    - name: Commit PDFs to Control Repo
      run: |
        cd $GITHUB_WORKSPACE
        git add outputs/*.pdf
        git commit -m "Add/update PDFs for hands-on labs"
        git push origin main

    # 6. Configure Git for Committing
    - name: Configure Git
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

