---
name: version

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: write
  pull-requests: write
  
jobs:
  increment-version:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Fetch the versioning branch
        run: |
          git fetch origin versioning:versioning
          git checkout versioning

      - name: Read the current version
        id: read_version
        run: |
          if [ ! -f VERSION ]; then
            echo "0.0.0" > VERSION
          fi
          CURRENT_VERSION=$(cat VERSION)
          echo "Current version is $CURRENT_VERSION"
          echo "current_version=$CURRENT_VERSION" >> $GITHUB_ENV

      - name: Increment version
        id: increment_version
        run: |
          IFS='.' read -r major minor patch <<< "$CURRENT_VERSION"
          patch=$((patch + 1))
          NEW_VERSION="$major.$minor.$patch"
          echo "$NEW_VERSION" > VERSION
          echo "New version is $NEW_VERSION"
          echo "new_version=$NEW_VERSION" >> $GITHUB_ENV

      - name: Commit and push the new version
        run: |
          git add VERSION
          git commit -m "Increment version to ${{ env.new_version }}"
          git push origin versioning
